##################################################################
# Configurações básicas do Spring e do JPA/JWT
##################################################################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backGenerico?useSSL=false
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  expiration: 864000000
  secret: segredoLoginABC


##################################################################
# Exibir logs no console da IDE
##################################################################
logging:
  level:
    org:
      springframework:
        security: DEBUG


# Porta padrão a ser usada
server:
  port: 8080